//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskmanagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Task
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Enter Task Title !!")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Please Enter Task Description !!")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Please Enter Task Due Date !!")]
        public Nullable<System.DateTime> Dates { get; set; }
    }
}
