//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskmanagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class UserInfo
    {
        public int id { get; set; }

        [Required(ErrorMessage ="Please Enter User Name !!!")]
        public string username { get; set; }


        [DataType(DataType.Password)]
        [RegularExpression("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[#$^+=!*()@%&]).{8,}$", ErrorMessage = "Please Enter Correct Password !!!")]
        [Required(ErrorMessage = "Please Enter Password !!")]
        public string password { get; set; }

        
        public string role { get; set; }
    }
}
